:call pathogen#infect()
syntax on
filetype plugin indent on
set encoding=UTF-8
set fileencoding=UTF-8
set expandtab
set tabstop=4
set shiftwidth=4
set nowrap
set number
set history=200

"NERDTree
autocmd vimenter * NERDTree
autocmd vimenter * wincmd w
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

"Colors
highlight Pmenu ctermbg=238 gui=bold
